### ISSUE TITLE
Doesn't support arm64 arch

### ISSUE THREAD

**Issue by djcp** [eaceaser/asdf-tilt#3]
Hello! Thanks for the plugin, it's been a big help. Unfortunately, it doesn't support arm64 architectures so it's not working on mac osx machines with m1 chips. I could probably submit a PR to fix this, but I wasn't sure if this was on your roadmap.

**Comment by eaceaser** [comment]
Not on my roadmap -- filing a PR is probably most expedient

**Comment by eaceaser** [comment]
fixed in #4  -- thanks!
